In [1]:
import pandas as pd

In [23]:
df = pd.read_csv('data.csv')
df.drop(columns=['vessel_name', 'imo', 'call_sign', 'cargo', 'transceiver'], inplace=True)
df.head()

,mmsi,base_date_time,longitude,latitude,sog,cog,heading,vessel_type,status,length,width,draft
0,368164470,2026-01-01 00:00:03,-76.31518,36.84956,0.0,149.6,19.0,52.0,0.0,20.0,8.0,2.3
1,366953930,2026-01-01 00:00:02,-74.20510,40.61131,0.0,250.4,191.0,52.0,0.0,27.0,16.0,4.0
2,367328790,2026-01-01 00:00:01,-97.16752,27.85969,0.0,11.2,34.0,31.0,12.0,207.0,22.0,3.1
3,368025040,2026-01-01 00:00:04,-122.50573,48.75658,0.0,NaN,NaN,37.0,NaN,13.0,4.0,NaN
4,368284370,2026-01-01 00:00:01,-90.46691,40.00764,4.7,79.2,NaN,31.0,12.0,347.0,33.0,3.0

In [24]:
df.columns

Index(['mmsi', 'base_date_time', 'longitude', 'latitude', 'sog', 'cog',
       'heading', 'vessel_type', 'status', 'length', 'width', 'draft'],
      dtype='str')

In [27]:
len(df)

4229555

In [30]:
# houston/galveston port
latitude_bounds = [28.5, 30.5]
longitude_bounds = [-96.5, -94.0]

df_houston = df[
    df['latitude'].between(*latitude_bounds) &
    df['longitude'].between(*longitude_bounds)
]

df_houston.head()

,mmsi,base_date_time,longitude,latitude,sog,cog,heading,vessel_type,status,length,width,draft
17,367631610,2026-01-01 00:00:00,-95.10202,29.77164,0.1,264.4,276.0,52.0,12.0,28.0,10.0,3.1
18,367754480,2026-01-01 00:00:00,-95.10097,29.74896,0.0,73.0,333.0,52.0,0.0,24.0,12.0,5.5
25,368088250,2026-01-01 00:00:06,-94.91993,29.68821,4.8,160.7,NaN,52.0,NaN,18.0,6.0,NaN
27,367451110,2026-01-01 00:00:02,-95.67220,29.06032,0.0,247.1,19.0,31.0,12.0,219.0,17.0,2.8
42,367654520,2026-01-01 00:00:01,-95.02351,29.70301,1.4,110.1,56.0,52.0,0.0,25.0,12.0,2.9

In [31]:
len(df_houston)

367919

In [32]:
df_houston.mmsi.unique()

array([367631610, 367754480, 368088250, ..., 368253140, 338249077,
       367680760], shape=(1016,))

In [38]:
test_id = 367631610
df_houston[df_houston['mmsi'] == test_id]

,mmsi,base_date_time,longitude,latitude,sog,cog,heading,vessel_type,status,length,width,draft
17,367631610,2026-01-01 00:00:00,-95.10202,29.77164,0.1,264.4,276.0,52.0,12.0,28.0,10.0,3.1
9632,367631610,2026-01-01 00:01:09,-95.10202,29.77164,0.0,200.3,277.0,52.0,12.0,28.0,10.0,3.1
20900,367631610,2026-01-01 00:02:20,-95.10202,29.77165,0.0,246.8,275.0,52.0,12.0,28.0,10.0,3.1
29041,367631610,2026-01-01 00:03:30,-95.10202,29.77164,0.0,244.5,275.0,52.0,12.0,28.0,10.0,3.1
29285,367631610,2026-01-01 00:06:00,-95.10202,29.77165,0.0,278.0,276.0,52.0,12.0,28.0,10.0,3.1
...,...,...,...,...,...,...,...,...,...,...,...,...
4203987,367631610,2026-01-01 12:04:21,-95.10203,29.77166,0.0,300.0,276.0,52.0,12.0,28.0,10.0,3.1
4205623,367631610,2026-01-01 12:05:29,-95.10202,29.77166,0.0,284.3,276.0,52.0,12.0,28.0,10.0,3.1
4208487,367631610,2026-01-01 13:40:50,-95.10202,29.77165,0.0,175.3,276.0,52.0,12.0,28.0,10.0,3.1
4216785,367631610,2026-01-01 13:42:00,-95.10201,29.77165,0.0,232.7,277.0,52.0,12.0,28.0,10.0,3.1
4228773,367631610,2026-01-01 13:43:09,-95.10201,29.77165,0.0,206.4,277.0,52.0,12.0,28.0,10.0,3.1